Revert "unsub from Auth"
This reverts commit e0801cf75fdf47fd24647829471cda9956420881.

Because onDestroy(authUnsub) caused
"TypeError: fn is not a function"
when loading the page